### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KOHPM** [bitfocus/companion-module-videolan-vlc#10]
Hello
No matter how we tried, naming Id song starting 1=3, 2=4, 3=5, etc ... we can't get the button to respond right. 
A
<img width="1106" alt="Screen Shot 2020-10-23 at 4 20 35 PM" src="https://user-images.githubusercontent.com/44657017/97050778-ff023f80-154b-11eb-8066-e8e9caaf3daa.png">ll t
![Uploading Screen Shot 2020-10-23 at 4.19.56 PM.png…](3 buttons (timer=5, intro=4, outro=3) ... all of them plays the same clip = 1=3
we put them one by one, restarted Companion and VLC .. nothing works for us.

Here are screen shot of what we're trying to achieve.
<img width="1097" alt="Screen Shot 2020-10-23 at 4 21 02 PM" src="https://user-images.githubusercontent.com/44657017/97050763-fad62200-154b-11eb-87d3-a0feb2fd9c81.png">

**Comment by istnv** [comment]
@KOHPM  Please try the latest build. It includes a lot of added VLC features.

**Comment by KOHPM** [comment]
> @KOHPM Please try the latest build. It includes a lot of added VLC features.
@istnv 

hmmm... are you referring to this one? The warning seems very strong. how possible could this be a show ruin?
[<img width="686" alt="Screen Shot 2020-11-10 at 11 36 36 AM" src="https://user-images.githubusercontent.com/44657017/98703570-a1dafc00-2349-11eb-894e-f5d7bddff11d.png">](https://bitfocus.io/companion/download/builds/)

**Comment by istnv** [comment]
Most of those builds are quite stable. Once in a while there may be a one that has show-stopping issues.
The warning is pretty dramatic and points out the possibility of a 'bad' version.
- Make a back-up copy of your current version.
- Install the new build and test before running (or ruining) a live show.
