### ISSUE TITLE
Trigger when countdown timer ends (feature request?)

### ISSUE THREAD

**Issue by gmcgrath86** [bitfocus/companion-module-videolan-vlc#19]
This module is super useful and the recent update with the timer is great!  Paired with the Yamaha QL1 module, this setup has been a game changer in our broadcast studio.  I was looking for a way to activate a trigger when the timer hits 0, but I'm not sure if this is currently possible.  Alternatively, the trigger could be activated when the player changes state from "playing" to "stopped."  Basically, I'd like to make stuff happen when the video ends.

   Is there a way to achieve this with the current module, or if not, could this be considered for a future update?  

Thanks!

**Comment by istnv** [comment]
Newer Companion updates should be able to do this with the triggers and internal variables.
