### ISSUE TITLE
Module crash on song skip

### ISSUE THREAD

**Issue by Simber1** [bitfocus/companion-module-videolan-vlc#21]
So I was able to crash the module by skipping a song quite a few times now by mistake but I can't repo it anymore.

![image](https://user-images.githubusercontent.com/16944153/102456818-ade96600-4039-11eb-8dab-7599ba6b32c0.png)

**Comment by istnv** [comment]
You have somehow generated an empty 'this is playing' response from VLC. I've tried several times (including a 20x per second skip button repeat). I can't reproduce this but I did add a check to catch and ignore the error instead of crashing.

**Comment by Simber1** [comment]
Cheers, I was playing by just selecting a load of files and hitting play, I had it happen quite a few times but I can’t repo it now which is annoying.

**Comment by Simber1** [comment]
On further testing this is caused by just playing loads of individual files back to back

**Comment by istnv** [comment]
You can overwhelm VLC with commands and it sometimes gives empty responses. There is an update on the way that will ignore those without crashing. I've been tinkering with a 400 song playlist and VLC may crash, but companion stays running.

**Comment by istnv** [comment]
Fixed as part of #22
