### ISSUE TITLE
Companion crash if VLC password is empty when plugin is enabled

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion-module-videolan-vlc#25]
If Lua HTTP Password  in VLC is empty (not set), Companion crashes when enabling VLC plugin on Win 10 (valid for latest stable Companion release 2.1.2 and for "companion-2.2.0-ef39a2d-2740-win64.exe", containing vlc module version 1.1.5 according to info log)

![bild](https://user-images.githubusercontent.com/4034632/102930969-c1fbf000-449d-11eb-8f22-3fd6bccf9c69.png)

**Comment by istnv** [comment]
Thanks for the comments. That will be fixed soon. 
For now, set the password in VLC before adding the module.

**Comment by istnv** [comment]
@Gartom Remember to restart VLC after setting the password.

**Comment by Gartom** [comment]
> Thanks for the comments. That will be fixed soon.

Thanks for that.

> For now, set the password in VLC before adding the module.

Yes, that's what I did to make it run. :-)
