### ISSUE TITLE
Youtube link in playlist fails module: cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by bastiaanrodenburg** [bitfocus/companion-module-videolan-vlc#27]
In VLC it's possible to include a Youtube link. This is accomplished by a lua file, you probably need to update it before it work. https://github.com/videolan/vlc/blob/master/share/lua/playlist/youtube.lua

Problem is that when this item is played while the companion module is connected I get an error:
![image](https://user-images.githubusercontent.com/56339487/103275222-04548e00-49c4-11eb-8797-115b2ad020d5.png)
Uncaught Exception: cannot read property 'name' of undefined
File ...\videolan-vlc\index.js:458:74.

I'm running companion 2.1.2 (f4bcaf3-2679).

**Comment by bastiaanrodenburg** [comment]
I just ran one from the sources and it seams to be solved already. Not sure why it's not in the nightly of companion. Probably not updated to the latest version of this module?

**Comment by istnv** [comment]
There were several modules needing review. This was included in yesterday's build 2.2.0-569d376-2769.
