### ISSUE TITLE
How add dynamic variables

### ISSUE THREAD

**Issue by Ron1963** [bitfocus/companion-module-videolan-vlc#29]
Hi, I'm completely new to Companion, but I can handle it a bit. If I look at all the dynamic variables of VLC I see this variable: $ (vlc: r_num). If I look at the buttonpresets, this variable is not in between them. Do I have to add a preset? How? Or do I have to do something else?

**Comment by istnv** [comment]
Standard Companion feature. Add the variable code `$(vlc:r_num)` to text area of the button you would like to show that information:
![image](https://user-images.githubusercontent.com/51003420/104135424-3f9c7880-5345-11eb-9da5-99fedc4bac53.png)
