### ISSUE TITLE
Feature Request:  Dynamic variable for count UP

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-videolan-vlc#31]
Would be great to be able to display both a count UP timer and Count DOWN.  We sometimes analyze clips and need to be able to see where we are from clip beginning.  Thanks!

**Comment by istnv** [comment]
This was just added a couple of days ago.

Var | Desc
-- | --
$(INSTANCENAME:e_time) | Elapsed time for Playing Item, variable size
$(INSTANCENAME:e_hhmmss) | Elapsed time for Playing Item as "HH:MM:SS"
$(INSTANCENAME:e_hh) | Elapsed time Hours for Playing Item
$(INSTANCENAME:e_mm) | Elapsed time Minutes for Playing Item
$(INSTANCENAME:e_ss) | Elapsed time Seconds for Playing Item
