### ISSUE TITLE
$(INSTANCENAME:pname_{num}) does not exist?

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion-module-videolan-vlc#32]
Hi everyone,

is it me or does the variable for the playlist item name not exist anymore?

Using companion 2.2.0 build 3251 and vlc 3.0.12 on win10

**Comment by istnv** [comment]
I just loaded that build. That variable pattern works fine. How are you typing the variable text?

**Comment by Fred-DTV** [comment]
It doesn't show in the dropdownlist when i start typing $(vlc

As you can see here, it doesn't show in the list of variables of the instance neither

![Screenshot 2021-04-19 at 18 12 41](https://user-images.githubusercontent.com/70434961/115268718-d9d93d00-a13a-11eb-9209-c8e57dd1f323.jpg)

**Comment by istnv** [comment]
Those are not a pre-defined variables. They are created based on the VLC playlist numbers and do not exist until you load a playlist.
It does not show up on the 'list' of variables, but it does work.

**Comment by Fred-DTV** [comment]
ah okay my bad. Thanks a lot
