### ISSUE TITLE
Feature request: VLC Volume control

### ISSUE THREAD

**Issue by juergen-miessmer** [bitfocus/companion-module-videolan-vlc#36]
> set volume level to <val> (can be absolute integer, percent or +/- relative value):

 ?command=volume&val=<val>
 Allowed values are of the form:
   +<int>, -<int>, <int> or <int>%

**Comment by andimanuel** [comment]
Very interested as well! Even just a mute function would be great for previewing a video.

**Comment by istnv** [comment]
Almost done with this. 'Volume' is supposed to be a value from 0 to 1024. 
Practical value is 0 to 320. (0 to 125%) '+' or '-' 1 is adjusts approximately 1/1024 
I could not get '%' to work using any known encoding (URL Encode %25).
