### ISSUE TITLE
Feature request: Delete item from playlist

### ISSUE THREAD

**Issue by lukestein** [bitfocus/companion-module-videolan-vlc#37]
Thank you for the help implementing playlist functions in #35. I'm hoping we can add what appears to be the http interface's one remaining playlist function: Deleting a specific item from playlist `?command=pl_delete&id=`.

I have implemented this but not sure the handling of a default ID is done the best way.

**Comment by istnv** [comment]
I've included your code as well as volume control in a new pull request.

FYI from the VLC docs:
> delete item <id> from playlist:
  ?command=pl_delete&id=<id>
  NOTA BENE: pl_delete is completly UNSUPPORTED
