### ISSUE TITLE
VLC remaining time and filenames not showing up in Companion on Mac OS

### ISSUE THREAD

**Issue by livevideosolutions** [bitfocus/companion-module-videolan-vlc#39]
Hi,

I have been struggling with this issue for a while now. Ik have setup VLC as advised and i can control start, stop, full-screen etc. But i'm not able to make the clip remaining time to work. I have tried reinstalling VLC, tried different settings but nothing worked.

I noticed when watching a video from someone installing VLS in companion that he did this with a Windows system and when he add's the VLS instance he has two more options that the apple version does not have. 

These two options are "number of clip names to reserve" and a option that sets "use - for empty?". Maybe that has something to do with it. 

Any help would be greatly appreciated.

Hans

**Comment by istnv** [comment]
These features are in the Beta builds

**Comment by lukestein** [comment]
Sorry for the difficulty, @livevideosolutions. Can confirm that the requested functions are working (for me) on Mac under recent Companion beta downloads:
![image](https://user-images.githubusercontent.com/44452336/117474153-a6fbbb00-af28-11eb-8425-36fecfc94685.png)

**Comment by livevideosolutions** [comment]
Oké good to know that it can work on a mac! Thanks @lukestein. I haven't tried the beta versions 2.2 only the standard version. I will give that a try tomorrow.

**Comment by lukestein** [comment]
I'm not generally a big beta user, but the Companion builds seem impressively stable, and there's a lot of stuff that's not in the release version (yet).

**Comment by livevideosolutions** [comment]
Well, it works!!! O man i'm so happy i got this to work finally! The beta version 2.2. was the solution. So thanks for pointing me in the right direction @lukestein .
