### ISSUE TITLE
Preset play list buttons

### ISSUE THREAD

**Issue by brianteeman** [bitfocus/companion-module-videolan-vlc#42]
## Expected behaviour
The value for number of clip names to reserve is used in the preset buttons
![image](https://user-images.githubusercontent.com/1296369/130665073-ff94306f-fa41-49d9-9a56-678c2c679681.png)

## Actual behaviour
Only 5 preset play list buttons are displayed

![image](https://user-images.githubusercontent.com/1296369/130665174-8a5f4d3e-1c92-4de5-8c91-a9cd44ff1fc2.png)

### Build version
2.2.0 (2.2.0-56056c0b-3505)
### Operating System
Windows 10
### Browser
Chrome

**Comment by istnv** [comment]
'Reserved' clip names is to prevent $NA from appearing on the button when a playlist does not have a particular item #. They are not related to presets. The presets are demonstration/example buttons to better document how some actions may be used.

**Comment by brianteeman** [comment]
imho if you have 10 'reserved' then there should be 10 presets as this documents and provides examples to better document hos they can be used.

**Comment by istnv** [comment]
The only difference between playlist presets is the Clip ID.  Extra presets do not add any useful information and simply take up more memory. You can copy preset 1 and edit the Clip number for any over 5.
