### ISSUE TITLE
Missing Variables

### ISSUE THREAD

**Issue by brianteeman** [bitfocus/companion-module-videolan-vlc#43]
The preset play list buttons use a variable `$(vlc:pname_X)` in the button text and it appears to work

This variable is not present in the list of available variables

If you try to copy the text to another button or edit the button etc you get an error

![image](https://user-images.githubusercontent.com/1296369/130665702-b34d5446-d486-4de4-9bf5-6a3faec03a18.png)

![image](https://user-images.githubusercontent.com/1296369/130665821-8ae391d3-8d1d-48a6-b67d-49bdd0513635.png)

### Build version
2.2.0 (2.2.0-56056c0b-3505)

### Operating System
Windows 10

### Browser
Chrome

**Comment by istnv** [comment]
The variables are created dynamically from the VLC data. they are not in the usual GUI 'list' of variables. This does result in a error from the GUI, but the button text will be correct.

**Comment by brianteeman** [comment]
ok - strange but weird.
