### ISSUE TITLE
Enhancement: VLC Seek to read Custom Variables

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-videolan-vlc#47]
Currently the "vlc: Seek To" Action requires a number in the field. 

It would be useful if the field could read Custom Variables. This way, the user could store a specific timecode  to a Custom Variable, and then recall that Custom Variable to "Seek" in VLC. 

Here's an example screen-shot using a Custom Variable called "tc" (timecode) to seek the play position to 0:24: 

<img width="587" alt="vlc-seek-read-variable" src="https://user-images.githubusercontent.com/76959770/196974362-9c786df1-6612-4cbd-bd4a-91939c1db59e.png">

**Comment by davidjoshuaford** [comment]
Similar suggestion is to have the Play ID action be able to read custom variables. That would allow us to pre-load a clip number and have it play back that number – 
<img width="458" alt="Screen Shot 2022-10-20 at 3 52 25 PM" src="https://user-images.githubusercontent.com/76959770/197045136-af11bad6-9fee-43e0-bc7c-1fec52548f22.png">

**Comment by istnv** [comment]
> Currently the "vlc: Seek To" Action requires a number in the field.
> 
> It would be useful if the field could read Custom Variables. This way, the user could store a specific timecode to a Custom Variable, and then recall that Custom Variable to "Seek" in VLC.
> 

This one should be pretty easy.


> Similar suggestion is to have the Play ID action be able to read custom variables

This one needs a little more work. The module's ID is not the same as VLC internal ID.

**Comment by davidjoshuaford** [comment]
Thanks! I'll check it out
