### ISSUE TITLE
Connection to VLC 3.0.0 and up

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-videolan-vlc#5]
By default, the web interface is completely locked down – it’s restricted to localhost. To allow access from other computers, you’ll have to edit the web interface’s .hosts file.

This link covers how the process is done, at least for now:
[https://www.howtogeek.com/117261/how-to-activate-vlcs-web-interface-control-vlc-from-a-browser-use-any-smartphone-as-a-remote/](https://www.howtogeek.com/117261/how-to-activate-vlcs-web-interface-control-vlc-from-a-browser-use-any-smartphone-as-a-remote/)

Key Info File Location:
- Windows: C:\Program Files (x86)\VideoLAN\VLC\lua\http (use “Program Files” instead of “Program Files (x86)” on 32-bit versions of Windows.)
- Mac OS X: /Applications/VLC.app/Contents/MacOS/share/lua/http/.hosts
- Linux: /usr/share/vlc/lua/http/.hosts

*This is partially a reminder to write up some info about the process inside the module or link to a page here on GitHub if the other link breaks*

**Comment by EventReplay** [comment]
@McHauge I've had a good play with this and can confirm Playlist ID does work! It just is not quite straight forward as ID's start @ 3 Not sure why? (This is stated here: https://github.com/bitfocus/companion-module-vlc/issues/3#issuecomment-523689906) so the ID in the playlist 1=3 2=4 etc in my tests.

I would say any issues that users are having with this module are firewall issues.

**Comment by McHauge** [comment]
Lovely, I'll try and make it so the module adds +2 so 1 becomes 3, 2 becomes 4 and so on, would this make it harder or easier to use?

**Comment by EventReplay** [comment]
I guess it would be good and makes sense to match ID's in playlist, but I'm unsure what implications it might have if you say changed order and therefore ID in playlist. prob need to know why ID starts @ 3?

**Comment by irvtech** [comment]
@McHauge Hi Andreas. Thank you for creating the module. I got it up and running to control a VLC running on a networked PC from my Mac-connected Stream Deck running Companion 2.0.

All of the commands work for me with the exception of "Play ID". I have 5 clips in a playlist. I've programmed my first button with an ID of 3, second button with clip 4 and so on. Regardless of which button I press, only the first clip in the playlist is triggered. Any thoughts?

**Comment by EventReplay** [comment]
@irvtech I've had a look at this again and done a few more tests, Latest vlc 3.0.10, Current Companion v2. I'm not having any problems getting my 3 clips to play using Clip Nr, I'm using PC to PC.
Give this a try:
1. Clear your playlist
2. Add Clips 1 at a time

The First Clip you add Clip Nr =3
The Second Clip you add Clip Nr =4
and so on!

I think Clip Nr is related to the order you add to your playlist! So even if you change order of clips in the playlist the Clip Nr stays atached to the Clip as above. Thats how it worked for me in my brief test. ID seems a bit missleading.

Let me know how you get on.

**Comment by irvtech** [comment]
Thanks. I tried with a fresh playlist and it worked on the first press. Thanks for an excellent tool.

Cheers,

Andrew

**Comment by Rahulhasmail** [comment]
Thanks 
Can I also Seek Help on the same, 
as Suggested @irvtech we also tried 

The First Clip you add Clip Nr =3
The Second Clip you add Clip Nr =4
and so on!

its working but if we can able to achieve 
1=1
2=2
3=3
4=4 and so on will be nicer and easy to understood by team members:

Please help

Thanks
