### ISSUE TITLE
VLC Feedback not working in v3.0 betas

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-videolan-vlc#53]
In version 3.0 beta 5746, VLC's feedback no longer works for: 

```
vlc: Item state
vlc: Loop mode
vlc: Repeat mode
vlc: Shuffle mode
vlc: Full Screen
```

Thanks!

**Comment by istnv** [comment]
A quick glance looks like the v2.x to v3.x upgrade conversion does not properly re-configure these for v3 format.

**Comment by davidjoshuaford** [comment]
Thanks!

One more thing to add which is _sort of_ related to these commands:

```
vlc: Loop mode
vlc: Repeat mode
vlc: Shuffle mode
vlc: Full Screen
```

Currently the Actions for the above ONLY toggle states. 

It would be a great benefit to have the option to choose the Action to be either Toggle/ On/ Off. 

For example, if you have one specific video background that loops for supersource, you want to know for sure that Repeat One is ON. Or, if you're playing a list of videos, you want to know for sure that the Loop or Repeat modes are OFF.

Thanks again!
David

**Comment by istnv** [comment]
I added those options to the update. Still waiting for inclusion.
VLC only has toggle commands, but when the feedback was added, the module mostly knows the player state.

**Comment by davidjoshuaford** [comment]
Thanks John, you're saying that VLC itself doesn't have the options for On/Off, only toggle?

Or that Companion currently just doesn't have On/Off built in?

**Comment by istnv** [comment]
Both. The VLC API only has a toggle option.
The module evolved in pieces around available features in Companion, but I can simulate ON/OFF looking at the feedback status. On/Off is in the waiting update.

**Comment by davidjoshuaford** [comment]
Interesting! Yes I was wondering if a work around could be checking the current status and then initiating a toggle press or not depending if On or Off was required. Thanks for the explanation.

**Comment by istnv** [comment]
I also added a true/false to the feedback (color) for triggers/variables. Had to do that in the XAir module, too.
While Companion has a 'Set variable on condition', it only responds to true(on), but that leaves no way to turn 'off' the variable.
In the beta pipeline is a new test for 'condition not true'. 
Until then, the VLC feedback now has a false option you can test for. Feedback state -> is false -> yes -> set variable

**Comment by davidjoshuaford** [comment]
Great, I'll check it out!
