### ISSUE TITLE
VLC Volume Up for Companion 3.0

### ISSUE THREAD

**Issue by jluc101** [bitfocus/companion-module-videolan-vlc#61]
When I use "Set Volume" action to go down by a value like -25 I can use a button to go down in increments of approx. 10%. However the same does not work when I set volume to +25. This worked in 2.4.2 NOT in 3.0

**Comment by istnv** [comment]
I'll take a look over the weekend.

**Comment by istnv** [comment]
Fixed in latest release (v2.2.1)

**Comment by jluc101** [comment]
You're the best. It works just as advertised
