### ISSUE TITLE
Jump Backward, Jump Forward

### ISSUE THREAD

**Issue by AlexHasker** [bitfocus/companion-module-videolan-vlc#65]
Could the Very short, shot, medium and long lump forward and backward VLC "hotkeys" get added to Companion to help skip through clips and skip back ? 

![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/45926058/8e0d684a-5594-49cf-9422-c36194594bed)

**Comment by istnv** [comment]
Those can be created with the 'Seek to' command that is in the VLC module.
