### ISSUE TITLE
Loop feedback

### ISSUE THREAD

**Issue by FirelightLokeren** [bitfocus/companion-module-videolan-vlc#73]
Is it possible to get a feedback if loop is active or not?
Kind Regards
Koen

**Comment by istnv** [comment]
Already there:
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/51003420/30dff089-1a9a-4292-b07c-6af81db7b312)

**Comment by FirelightLokeren** [comment]
OK , Just a new user.

When you usen the presets the feed back was working for the other buttons. On the feedback the "loop mode" status in on "undifined"

Kind redards.

Koen

**Comment by istnv** [comment]
The connection must be enabled for any of the actions or feedbacks to be active and fully defined:
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/51003420/d709e769-5422-42f6-bd4c-74eac9dde19a)
Green toggle on the right will enable/disable the connection.

**Comment by istnv** [comment]
OK. I see the problem is the presets. Thanks.

**Comment by istnv** [comment]
This should be fixed in the downloads in the next day or so.
