### ISSUE TITLE
Pause/Resume/Toggle has no effect when stopped

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-videolan-vlc#76]
Howdy! 

As the title says, the action `vlc: Pause / Resume `does not work if the player is stopped. 

I recall that in previous versions, if the player was stopped, this action would bump it into play by default, and then pause/ resume toggle after that. 

Can that behavior be reinstated? Or do we need to use the play button separately? 

Thanks, 
David

**Comment by istnv** [comment]
There was some logic changes earlier to accommodate 'Pause' _on/off_ which needs to compare against the current playing status as VLC has only a toggle option. 
I'll check again to see if toggle is being skipped.

**Comment by istnv** [comment]
Yup. Got lost in the logic :(.
Should be fixed in betas by tomorrow.

**Comment by davidjoshuaford** [comment]
Amazing, thank you John!

Yeah it looks like both the Resume and Toggle options don't bump it into Play.
