### ISSUE TITLE
VLC Module current time/total length/remaing time of a playing clip

### ISSUE THREAD

**Issue by hsteppke** [bitfocus/companion-module-videolan-vlc#8]
Like on the Hyperdeck module a few internal variable would be nice that holds the following timers.

time (current postion)
length (total lenght of clip time)
remain (length - time)

The variable will likely hold values in seconds so something like:
time_hms
length_hms
remain_hms 
printing the seconds as hh:mm:ss would be better i guess.

This variables are available via the Webinterface of VLC polling the Status Interface at http://$IP:$Port/requests/status.xml
like: http://127.0.0.1:8080/requests/status.xml

see https://wiki.videolan.org/VLC_HTTP_requests/ 

it respond with an XML starting like:
<root>
<fullscreen>false</fullscreen>
<aspectratio>default</aspectratio>
<audiodelay>0</audiodelay>
<apiversion>3</apiversion>
<currentplid>6</currentplid>
<time>969</time>
<volume>333</volume>
<length>8873</length>
<random>false</random>
......

where  "<time>###</time>" is the current position and "<length>###</length>" is the total length of the currently playing file in Seconds.

In the Hyperdeck Module there is a similar solution in place, a poller is started if enabled that on a configurable Intervall fetches the transportInfo and provides that info.

In the QLAB Advanced Module using TCP there is a similar function that requests that data for the current cue and lists like:
$(INSTANCENAME:r_hhmmss): Remaining time for Running Cue as "HH:MM:SS"
$(INSTANCENAME:r_hh): Hours left for Running Cue
$(INSTANCENAME:r_mm): Minutes left for Running Cue
$(INSTANCENAME:r_ss): Seconds left for Running Cue

Which is maybe the most important anyway. The time left until the current clip end.

**Comment by istnv** [comment]
@hsteppke Please try the latest build. It includes a lot of new VLC features.

**Comment by obcocav** [comment]
This would be a huge feature for us also!  Really looking for current time position (time played) in track as a variable rather than time remaining.  We use videos in a lecture/class environment sometimes and the teacher will ask to start and stop at position XX:XX.  As of now I have to go through his cue list and do the math to get time remaining for those points.  Thanks.
