### ISSUE TITLE
problems deleting titles in vlc from companion

### ISSUE THREAD

**Issue by dve2021** [bitfocus/companion-module-videolan-vlc#80]
hi,

In companion, the VLC_xxxx: Clear Playlist function does not clear the last button indicating the title ($(VLC_portable:pname_x)) from the VLC title list.

For the moment, to delete all the titles on the companion buttons, I have to add one more title to the playlist that I do not display on companion to avoid this problem.
 
On the other hand, all the titles are removed from the VLC playlist.

![loading files](https://github.com/bitfocus/companion-module-videolan-vlc/assets/98225618/3ba4a09a-4a13-4cb4-940d-5b145cdf47fb)

![after clear playlist](https://github.com/bitfocus/companion-module-videolan-vlc/assets/98225618/cde5a5a6-db9f-45f7-bedd-2fa9fc4a413a)

Thank you for your answers

**Comment by istnv** [comment]
You did not answer my last question on FB. 
I may still have found the problem. I'll push a fix later today.

**Comment by dve2021** [comment]
hi John,

your last question was?

 How many items in your playlist? What is the 'Number of clip names to
reserve'? I am still trying to reproduce the problem.

if it's this one, I may not have been clear but I thought I answered:
in the current case there are 6 files, but if there are 2 or more on a
page, the problem remains the same for the last one

don't hesitate to put it back to me if it's not this one

thank you for your reply

Cordialement

Dominique Villemagne
04 77 94 37 31



Le lun. 1 janv. 2024 à 22:23, John Knight Jr ***@***.***> a
écrit :

**Comment by istnv** [comment]
'The number of clip names to reserve' is where the problem happens.
It will be fixed in a couple of hours.

**Comment by dve2021** [comment]
john

were you able to reproduce the problem?

**Comment by istnv** [comment]
Fixed with #81

**Comment by istnv** [comment]
It will be in the beta release sometime today.

**Comment by dve2021** [comment]
John,
Tell you about the beta version for Companion PI?

**Comment by istnv** [comment]
It is in the repository. You should be able to upgrade the PI manually. I do not update my Pi that often so I do not know the exact procedure.

**Comment by dve2021** [comment]
ok thank you for the information and the correction
