### ISSUE TITLE
Save button disabled for IPs with a two-digit last octet

### ISSUE THREAD

**Issue by nickgnat** [bitfocus/companion-module-videolan-vlc#88]
Version 3.4.0 (3.4.0+7015-main-c61cc19c)
Docker image

In the VLC module, "Save" is grayed out after entering an IP address with a two-digit number in the last octet.

For example: 192.168.0.9 allows "Save":
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/1111010/9dcaa1e5-0c73-40ca-aa44-3c7d1a1ba95b)

But 192.168.0.19 doesn't:
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/1111010/676d6d08-5add-4593-8424-48e6f51e6040)

A three-digit last octet seems fine too:
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/1111010/6a917a44-11ea-4090-827e-96d47f827175)

I've tested with many different values in the first 3 octets of the IP address, and this behavior has been consistent. As a workaround, I am able to save the module with the first digit entered (for example: 192.168.0.4) and the other information correct, and then type another digit and save again (eg 192.168.0.41).

**Comment by istnv** [comment]
The original test for IP and Hostname had a couple of issues. 
The updated version will be in the betas today.
Until then, you can add a leading '0': `192.168.0.019`
