### ISSUE TITLE
Warning Message and no connection

### ISSUE THREAD

**Issue by MarkyMcFly610** [bitfocus/companion-module-videolan-vlc#90]
I try to connect VLC and companion.

I tried different versions of both softwares but I always  get the following warning in companion, and no connection.

could someone please help me?

Warning Message

<!doctype html> <html lang="en"> <head> <meta charset="utf-8" /> <link href="/img/icons/256x256.png" rel="shortcut icon" /> <link rel="manifest" href="/manifest.json" />  <meta name="theme-color" content="#000000" />  <link rel="apple-touch-icon" sizes="16x16" href="/img/icons/16x16.png" /> <link rel="apple-touch-icon" sizes="32x32" href="/img/icons/32x32.png" /> <link rel="apple-touch-icon" sizes="48x48" href="/img/icons/48x48.png" /> <link rel="apple-touch-icon" sizes="128x128" href="/img/icons/128x128.png" /> <link rel="apple-touch-icon" sizes="256x256" href="/img/icons/256x256.png" /> <meta name="viewport" content="width=device-width, initial-scale=1.0 , maximum-scale=1.0, user-scalable=0" /> <meta name="language" content="en" /> <meta name="google" content="notranslate" /> <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <meta http-equiv="Content-Language" content="en" /> <meta name="theme-color" content="#000000" /> <meta name="description" content="Bitfocus Companion - Admin" /> <title>Bitfocus Companion - Admin</title> <script type="module" crossorigin src="/assets/index-DFOWECnU.js"></script> <link rel="stylesheet" crossorigin href="/assets/index-BeHhMqeG.css"> <script type="module">import.meta.url;import("_").catch(()=>1);(async function*(){})().next();if(location.protocol!="file:"){window.__vite_is_modern_browser=true}</script> <script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy chunks, syntax error above and the same error below should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script> </head> <body> <noscript>You need to enable JavaScript to run Companion.</noscript> <div id="root"></div> <script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script> <script nomodule crossorigin id="vite-legacy-polyfill" src="/assets/polyfills-legacy-DzFawMcf.js"></script> <script nomodule crossorigin id="vite-legacy-entry" data-src="/assets/index-legacy-fckjhKxA.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script> </body> </html>

**Comment by istnv** [comment]
The VLC module is not set properly. The network port needs to be set to the port that VLC is listening on.
You have it set to the Companion port (that is the GUI page in the warning message)

**Comment by MarkyMcFly610** [comment]
Thank you for your help.

 I will try this tomorrow, but I think i setup everything right.

I can make some screenshots of the settings in VLC.

**Comment by istnv** [comment]
Based on your data, the target port is set to Companion and not the VLC program. VLC and Companion can not use the same port number at the same time.
![image](https://github.com/bitfocus/companion-module-videolan-vlc/assets/51003420/30adf4b4-8871-44fe-b75c-43f93366f01d)

**Comment by DavidTNguyen** [comment]
Is this where the password need to be set for VLC to match with the above screenshot by @istnv 
![image](https://github.com/user-attachments/assets/7f176dc6-e575-42a8-92f7-c3424986de96)

**Comment by istnv** [comment]
@DavidTNguyen 
That is correct. If you look at the help document (Click on the (?)) you will find that page with the password highlighted:
![image](https://github.com/user-attachments/assets/072ba65a-bf27-4868-a40c-1383c3c748dc)
