### ISSUE TITLE
Media information/Metadata Variables

### ISSUE THREAD

**Issue by jluc101** [bitfocus/companion-module-videolan-vlc#94]
I would love the ability to pull Media information & Metadata into Bitfocus Companion as a Variable.

Ex. Title, Artist, etc (perferably the full list as shown below). This would allow me to send the information back into places like OBS to display information in my streams as videos change.

![Screenshot 2024-09-18 003129](https://github.com/user-attachments/assets/8a4ec27b-7aaa-4d9e-b944-ef2b902f596f)
![Screenshot 2024-09-18 003146](https://github.com/user-attachments/assets/9328d258-f687-4877-a149-7bbdbb8be7b2)

**Comment by istnv** [comment]
The remote API for VLC does not provide any information except the Title.
